### ISSUE TITLE
Attribution for gerber files.

### ISSUE THREAD

**Issue by bspsbee** [math0ne/keyboard-gherkin#1]
Please add an attribution to the original source of the gerber files.

**Comment by cyril279** [comment]
Please add attribution to the original source of the gerber files.

**Comment by RichardBronosky** [comment]
To be fair, the original author of the gerber files is pretty hard to identify. I found this repo because [the original author linked here](https://www.40percent.club/p/license-violators.html). But, their own git hosting site is down and they never identify themselves on their site or in their code. How are you supposed to attribute someone who doesn't attribute themselves?

**Comment by math0ne** [comment]
@di0ib I have added attribution as requested at: https://www.40percent.club/p/license-violators.html

I'm skeptical I'm violating anything though as I did not change the attribution for the PCB directory, it is an exact clone of the original.
